# fly.toml app configuration file generated for supply-app-backend on 2026-05-08T01:06:22+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'supply-app-backend'
primary_region = 'ams'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256

[env]
SPRING_PROFILES_ACTIVE = "prod"
